<?php

return [
    '40up_a4' => [
        'name' => '40 per A4 sheet (52.5 x 29.7 mm)',
        'paper' => 'A4',
        'orientation' => 'P',
        'page_width' => 210,
        'page_height' => 297,
        'cols' => 4,
        'rows' => 10,
        'margin_top' => 0,
        'margin_left' => 0,
        'gutter_x' => 0,
        'gutter_y' => 0,
        'cell_width' => 52.5,
        'cell_height' => 29.7,
        'cell_padding' => 4,
        'barcode_height' => 8,
        'code_font_pt' => 8,
        'name_font_pt' => 7,
        'fill' => 'row',
        'supports_skip' => true,
    ],

    '62x29_thermal' => [
        'name' => '62 x 29 mm thermal (1 per page)',
        'paper' => [62, 29],
        'orientation' => 'L',
        'page_width' => 62,
        'page_height' => 29,
        'cols' => 1,
        'rows' => 1,
        'margin_top' => 0,
        'margin_left' => 0,
        'gutter_x' => 0,
        'gutter_y' => 0,
        'cell_width' => 62,
        'cell_height' => 29,
        'cell_padding' => 4,
        'barcode_height' => 15,
        'code_font_pt' => 10,
        'name_font_pt' => 10,
        'fill' => 'row',
        'supports_skip' => false,
    ],
];
